apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  ConnectionStrings__PedidoDbContext: SG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlO1BvcnQ9NTQzMjsRQSUyMENvbW1vbmxvZz1wZWRpY29kZTtVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPTEyMzs=
  ConnectionStrings__CatalogoDbContext: SG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlO1BvcnQ9NTQzMjsRQSUyMENvbW1vbmxvZz1wZWRpY29kZTtVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPTEyMzs=
