apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: jonasaraldi/fiap-fastfood:1.0.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: 1
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-configmap
