apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  ConnectionStrings__PedidoDbContext: "Host=postgres-service.fastfood.svc.cluster.local;Port=5432;Database=pedido;User Id=admin;Password=admin;"
  ConnectionStrings__CatalogoDbContext: "Host=postgres-service.fastfood.svc.cluster.local;Port=5432;Database=catalogo;User Id=admin;Password=admin;"
  ConnectionStrings__PagamentoDbContext: "Host=postgres-service.fastfood.svc.cluster.local;Port=5432;Database=pagamento;User Id=admin;Password=admin;"