apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  ConnectionStrings__PedidoDbContext: "SG9zdD1mYXN0Zm9vZC1wcm9kdWN0aW9uLmNscW04bzRrY3ZtLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtQb3J0PTU0MzI7RGF0YWJhc2U9cGVyam9zZTtVc2VyIElkPWluc3RydWN0aW9uO1Bhc3N3b3JkPXBvc3RyZXM7"
  ConnectionStrings__CatalogoDbContext: "SG9zdD1mYXN0Zm9vZC1wcm9kdWN0aW9uLmNscW04bzRrY3ZtLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtQb3J0PTU0MzI7RGF0YWJhc2U9Y2F0YWxvZ287VXNlciBJZD1wb3N0cmVzO1Bhc3N3b3JkPXBvc3RyZXM7"
  ConnectionStrings__PagamentoDbContext: "SG9zdD1mYXN0Zm9vZC1wcm9kdWN0aW9uLmNscW04bzRrY3ZtLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTtQb3J0PTU0MzI7RGF0YWJhc2U9cGFnbWVudG87VXNlciBJZD1wb3N0cmVzO1Bhc3N3b3JkPXBvc3RyZXM7"